#server.port=9000
#server.servlet.context-path=/journal
#spring.mongodb.uri=mongodb+srv://kjcwn:scik3@cluster0.tt6d7uv.mongodb.net/journaldb?retryWrites=true&w=majority
#
#spring.mongodb.database=journaldb
#spring.mongodb.auto-index-creation=true
##mvn clean package -D spring.profiles.active=dev
#
#weather.api.key= 793284781u429848943
#
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=hdcbjenkj@gmail.com
#spring.mail.password=ndbjwdbs
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
