server.port=9000
server.servlet.context-path=/journal
spring.mongodb.uri=mongodb+srv://hrishi:Hrishi123@cluster0.tt6d7uv.lksd.net/journaldb?retryWrites=true&w=majority

spring.mongodb.database=journaldb
spring.mongodb.auto-index-creation=true
#mvn clean package -D spring.profiles.active=dev