spring.mongodb.uri=mongodb+srv://hrishi:ornGL4U3DWKozEQQ@cluster0.mvhb6or.mongodb.net/journaldb?retryWrites=true&w=majority
spring.mongodb.database=journaldb
spring.mongodb.auto-index-creation=true
server.port=9000